<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.9.1.1 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 9484 2006-10-03 13:11:22Z nijel $
 * Date: Mon, 15 Jan 2007 19:44:26 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost (config:mayball) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['controluser'] = 'mayball_admin';
$cfg['Servers'][$i]['controlpass'] = "XuthebAw97";
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'mayball_admin';
$cfg['Servers'][$i]['password'] = 'XuthebAw97';
$cfg['Servers'][$i]['only_db'] = 'mayball';

/* End of servers configuration */

$cfg['ThemeDefault']='modan';

?>
